[package]
name = "polaroid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.67"
dimensioned = "0.8.0"
magick_rust = { version = "0.17.0", features = ["disable-hdri"] }
